spring.application.name=auth.app.backend
server.port=8082

#Database Configurations
spring.datasource.url=jdbc:mysql://localhost:3306/auth_app_system
spring.datasource.username=root
spring.datasource.password=Komal@325740


#JDBC Configurations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Hikari Configurations
spring.datasource.hikari.pool-name=HikariCP
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=18000000
spring.datasource.hikari.maximum-pool-size=5

logging.level.org.springframework.security=debug
logging.level.org.springframework=INFO
server.error.include-stacktrace=always

#JWT Configurations
security.jwt.secret=${JWT_SECRET:lcAfLlnPwjIJiCkmOu5+3jx65fOI9OGVpnjHrLly7MOeASjv2y+ZsyCF2imGXXvkyN3fhfrHI2gjMLAP5IFk0g==}
security.jwt.access-ttl-seconds=${JWT_ACCESS_TTL_SECONDS:3600}
security.jwt.issuer=${JWT_ISSUER:auth.app}
#Refresh Token - It is used to get a new access token when the old one expires, without asking the user to log in again.
security.jwt.refresh-ttl-seconds=${JWT_REFRESH_TTL_SECONDS:86400}
security.refresh-token-cookie-name=${JWT_REFRESH_COOKIE_NAME:refreshToken}
security.cookie-secure=${JWT_COOKIE_SECURE:true}
security.cookie-http-only=${JWT_COOKIE_HTTP_ONLY:true}
security.cookie-same-site=${JWT_COOKIE_SAME_SITE:lax}




